export const SKILL_COLOR_PALETTE = {
  amber:  '#F0B429',
  blue:   '#4B7BF5',
  teal:   '#2DD4C8',
  orange: '#F07832',
  purple: '#A78BFA',
  pink:   '#F472B6',
  sky:    '#0EA5E9',
  green:  '#22C55E',
  red:    '#EF4444',
} as const;

// Plain object — keys are lowercase, values are hex colors
const SKILL_COLORS: Record<string, string> = {
  // ── Languages ──────────────────────────────────────────
  'python':        '#F0B429',
  'javascript':    '#F0B429',
  'typescript':    '#F0B429',
  'c++':           '#F0B429',
  'java':          '#F0B429',
  'sql':           '#F0B429',
  'html/css':      '#F0B429',
  'embedded c':    '#F0B429',
  'matlab':        '#F0B429',
  'simulink':      '#F0B429',
  'bash':          '#F0B429',

  // ── ML & AI ────────────────────────────────────────────
  'pytorch':           '#4B7BF5',
  'tensorflow':        '#4B7BF5',
  'scikit-learn':      '#4B7BF5',
  'rl':                '#4B7BF5',
  'maml':              '#4B7BF5',
  'gnns':              '#4B7BF5',
  'gnn/gat':           '#4B7BF5',
  'ppo':               '#4B7BF5',
  'stable-baselines3': '#4B7BF5',
  'gym':               '#4B7BF5',
  'meta-learning':     '#4B7BF5',
  'nlp':               '#4B7BF5',
  'computer vision':   '#4B7BF5',
  'distilbert':        '#4B7BF5',
  'gemini ai':         '#4B7BF5',
  'graph-based rl':    '#4B7BF5',
  'q-prop':            '#4B7BF5',
  'shap':              '#4B7BF5',
  'shap/lime':         '#4B7BF5',
  'rf-detr':           '#4B7BF5',
  'xgboost':           '#4B7BF5',
  'pinn':              '#4B7BF5',
  'taxonomy design':   '#4B7BF5',
  'literature review': '#4B7BF5',
  'ai safety':         '#4B7BF5',

  // ── MLOps & Data ───────────────────────────────────────
  'airflow':        '#F07832',
  'mlflow':         '#F07832',
  'pandas':         '#F07832',
  'numpy':          '#F07832',
  'aws':            '#F07832',
  'aws s3':         '#F07832',
  'aws ec2':        '#F07832',
  'aws s3/ec2':     '#F07832',
  'docker':         '#F07832',
  'git':            '#F07832',
  'github actions': '#F07832',
  'ci/cd':          '#F07832',
  'linux':          '#F07832',
  'pandera':        '#F07832',
  'prometheus':     '#F07832',
  'hyperopt':       '#F07832',
  'domo':           '#F07832',
  'slack api':      '#F07832',

  // ── Robotics & Embedded ────────────────────────────────
  'ros 2':           '#A78BFA',
  'gazebo':          '#A78BFA',
  'gazebo fortress': '#A78BFA',
  'ardupilot':       '#A78BFA',
  'opencv':          '#A78BFA',
  'yolo11':          '#A78BFA',
  'yolo':            '#A78BFA',
  'nvidia jetson':   '#A78BFA',
  'jetson orrin nx': '#A78BFA',
  'jetson orin nx':  '#A78BFA',
  'sensor fusion':   '#A78BFA',
  'vins-mono':       '#A78BFA',
  'hitl':            '#A78BFA',
  'airsim':          '#A78BFA',
  'oak-d pro':       '#A78BFA',
  'slamtec c1':      '#A78BFA',
  'x500 urdf':       '#A78BFA',
  'bytetrack':       '#A78BFA',
  'bot-sort':        '#A78BFA',
  'rtmpose':         '#A78BFA',
  'cuda':            '#A78BFA',
  'arduino':         '#A78BFA',
  'pressure sensing':'#A78BFA',
  'solenoid control':'#A78BFA',
  'calibration':     '#A78BFA',

  // ── Web & Edge ─────────────────────────────────────────
  'react':              '#0EA5E9',
  'node.js':            '#0EA5E9',
  'express':            '#0EA5E9',
  'fastapi':            '#0EA5E9',
  'django':             '#0EA5E9',
  'cloudflare workers': '#0EA5E9',
  'hono':               '#0EA5E9',
  'deno':               '#0EA5E9',
  'cloudflare d1':      '#0EA5E9',
  'cloudflare r2':      '#0EA5E9',
  'drizzle orm':        '#0EA5E9',
  'chrome extension':   '#0EA5E9',
  'workers ai':         '#0EA5E9',
  'wrangler':           '#0EA5E9',
  'sidearm sports':     '#0EA5E9',
  'donor ux':           '#0EA5E9',
  'information architecture': '#0EA5E9',
  'digital fundraising':      '#0EA5E9',
  'brand strategy':           '#0EA5E9',
  'web strategy':             '#0EA5E9',

  // ── Databases ──────────────────────────────────────────
  'postgresql':       '#2DD4C8',
  'postgres':         '#2DD4C8',
  'mysql':            '#2DD4C8',
  'mongodb':          '#2DD4C8',
  'sqlite':           '#2DD4C8',
  'postgis':          '#2DD4C8',
  'pgvector':         '#2DD4C8',
  'etl':              '#2DD4C8',
  'pgadmin 4':        '#2DD4C8',
  'pgadmin':          '#2DD4C8',
  'active directory': '#2DD4C8',
  'cisco amp':        '#2DD4C8',
  'microsoft defender': '#2DD4C8',

  // ── Microsoft ──────────────────────────────────────────
  'azure ai':       '#F472B6',
  'copilot studio': '#F472B6',
  'power automate': '#F472B6',
  'power bi':       '#F472B6',
  'm365':           '#F472B6',
  'sharepoint':     '#F472B6',
};

export function resolveSkillColor(skill: string): string | undefined {
  return SKILL_COLORS[skill.trim().toLowerCase()];
}